kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: mintrcc
nodes:
  - role: control-plane
    extraPortMappings:
      # Grafana
      - containerPort: 30080
        hostPort: 3001
        protocol: TCP
  - role: worker
  - role: worker
