apiVersion: v1
kind: Secret
metadata:
  name: minio-secret
  namespace: o11y
type: Opaque
stringData:
  rootUser: minioadmin
  rootPassword: minioadmin
  accessKeyId: minioadmin
  secretAccessKey: minioadmin
