apiVersion: v1
kind: ServiceAccount
metadata:
  name: manager
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: manager
rules:
  - apiGroups: ["batch"]
    resources: ["jobs"]
    verbs: ["create", "get", "list", "watch", "delete"]
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: manager
subjects:
  - kind: ServiceAccount
    name: manager
roleRef:
  kind: Role
  name: manager
  apiGroup: rbac.authorization.k8s.io
