apiVersion: v1
kind: ConfigMap
metadata:
  name: elasticmq
data:
  elasticmq.conf: |
    include classpath("application.conf")

    node-address {
      protocol = http
      host = "*"
      port = 9324
      context-path = ""
    }

    rest-sqs {
      enabled = true
      bind-port = 9324
      bind-hostname = "0.0.0.0"
      sqs-limits = strict
    }

    queues {
      jobs {
        defaultVisibilityTimeout = 60 seconds
        receiveMessageWait = 0 seconds
        deadLettersQueue {
          name = "jobs-dlq"
          maxReceiveCount = 3
        }
        fifo = false
      }
      jobs-dlq { }
    }
