apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: o11y
  sources:
    - repoURL: https://grafana-community.github.io/helm-charts
      chart: grafana
      targetRevision: 12.1.1
      helm:
        valueFiles:
          - $values/k8s/helm/values/grafana.yaml
    - repoURL: https://github.com/z63d/minimum-trocco-alpha.git
      targetRevision: HEAD
      ref: values
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
